### ISSUE TITLE
MCDaemon字符串在代码中的拼写有少许错误

### ISSUE THREAD

**Issue by hanbings** [TISUnion/MCDaemon-go#10]
您好，我正在阅读MCDaemon-go项目，发现MCDaemon字符串在代码中的拼写有少许错误
它们在：
start.go
第10行
第17行
第24行
config/config.go
第30行
第126行
MCD_conf.ini
第6行
server/plugin.go
第38行
plugins/BackupPlugin/BackupPlugin.go
第31行
server/server.go
第54行

**Comment by lightbrotherV** [comment]
感谢指出问题！不过该项目已进入封存阶段，基本不怎么会去动它了，正在忙新坑 most-simple-mcd
