### ISSUE TITLE
是否有可能占用大量服务器资源？

### ISSUE THREAD

**Issue by Sciroccogti** [TISUnion/MCDaemon-go#11]
我在使用 MCDaemon-go 时，服务器经常报 "cannot keep up!"，甚至出现了服务器崩溃。今天尝试不使用 MCDaemon-go 开服，在几乎相同的玩家情况下，毫无警告。

测试并不严谨，仅供参考

这个 Issue 意图是想了解一下是否有同样情况的用户

**Comment by lightbrotherV** [comment]
MCD，肯定是会吃资源的，如果配置不是很高，勉强能跑原版端的话，那开MCD就会卡。
