### ISSUE TITLE
Linux 端 !!server restart 有问题

### ISSUE THREAD

**Issue by Sciroccogti** [TISUnion/MCDaemon-go#12]
目前每次执行重启都会输出 地图加载失败，然后退出

在 Windows 平台没有出现这一问题，但是 Windows 的测试环境是全新存档，所以不排除错误原因是存档太大。

**Comment by lightbrotherV** [comment]
可以直接看mc原生的logs, 我猜测是端口冲突。

**Comment by Sciroccogti** [comment]
呃是输入了`!!server restart` 啊，不是调用 `s.Restart()` 么，这应该是 MCDaemon-go 内部的冲突？
