### ISSUE TITLE
如何添加-javaagent 参数？

### ISSUE THREAD

**Issue by Sciroccogti** [TISUnion/MCDaemon-go#4]
您好，我想在开启服务端的时候使用`-javaagent`参数来调用[authlib-injector](https://github.com/yushijinhun/authlib-injector)。请问是否是在以下配置行编辑呢？

https://github.com/TISUnion/MCDaemon-go/blob/a59fdca478b1573be167946efa8a3b39c7f2f530/MCD_conf.ini#L6

以及具体格式大致是？

感谢！

PS：我注意到目前`run_environment`默认为`product`，似乎与https://github.com/TISUnion/MCDaemon-go/blob/a59fdca478b1573be167946efa8a3b39c7f2f530/README.md#L20
中描述的不一致。

**Comment by lightbrotherV** [comment]
目前java启动参数只有官方例子里的Xmx  Xms  nogui这3个，没有自定义参数的添加呢。

**Comment by shenjackyuanjie** [comment]
抱歉，我也不知道，不过，应该是在内个位置&nbsp;

沈瑗杰Jack


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lightbrother"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月12日(星期三) 下午3:22
收件人:&nbsp;"TISUnion/MCDaemon-go"<MCDaemon-go@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [TISUnion/MCDaemon-go] 如何添加java启动参数？ (#4)




目前java启动参数只有官方例子里的Xmx  Xms  nogui这3个，没有自定义参数的添加呢。

**Comment by Sciroccogti** [comment]
感谢，我注意到了在读取配置文件时，`[MCDeamon]` 似乎是作为标志位的，因此此处并不能添加参数。

https://github.com/TISUnion/MCDaemon-go/blob/a59fdca478b1573be167946efa8a3b39c7f2f530/config/config.go#L30
