### ISSUE TITLE
release-2.2闪退问题

### ISSUE THREAD

**Issue by GentlemanII** [TISUnion/MCDaemon-go#5]
看着B站tis的视频，修改了文件名，但是启动的时候窗口闪退。
环境：windows10 64位专业工作站版  版本1909（KB4524244）

**Comment by lightbrotherV** [comment]
> 看着B站tis的视频，修改了文件名，但是启动的时候窗口闪退。
> 环境：windows10 64位专业工作站版 版本1909（KB4524244）

修改了哪个文件？修改了哪些内容？

**Comment by GentlemanII** [comment]
谢谢大佬的回复！
修改了 jvm的最大内存 Xmx = 8192M和服务器启动文件名称


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lightbrother"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月25日(星期二) 晚上7:31
收件人:&nbsp;"TISUnion/MCDaemon-go"<MCDaemon-go@noreply.github.com&gt;;
抄送:&nbsp;"    Gentleman"<1306760802@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TISUnion/MCDaemon-go] release-2.2闪退问题 (#5)



 
看着B站tis的视频，修改了文件名，但是启动的时候窗口闪退。
 环境：windows10 64位专业工作站版 版本1909（KB4524244）
  
修改了哪个文件？修改了哪些内容？

**Comment by lightbrotherV** [comment]
# 服务器启动文件名称
server_name = server.jar

# 服务器启动文件, 完整路径为 server_path + '/' + server_name
server_path = minecraft

**Comment by GentlemanII** [comment]
还是闪退
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lightbrother"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月25日(星期二) 晚上7:37
收件人:&nbsp;"TISUnion/MCDaemon-go"<MCDaemon-go@noreply.github.com&gt;;
抄送:&nbsp;"    Gentleman"<1306760802@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TISUnion/MCDaemon-go] release-2.2闪退问题 (#5)




服务器启动文件名称
 
server_name = server.jar
 
服务器启动文件, 完整路径为 server_path + '/' + server_name
 
server_path = minecraft

**Comment by lightbrotherV** [comment]
> 谢谢大佬的回复！ 修改了 jvm的最大内存 Xmx = 8192M和服务器启动文件名称

服务器启动文件名称
server_name = server.jar
服务器启动文件, 完整路径为 server_path + '/' + server_name
server_path = minecraft
确包服务端路径是minecraft/server.jar

例子：
服务端路径：C:\\user\mincecraft\1.12.2-server.jar
server_name= 1.12.2-server.jar
server_path = C:\\user\mincecraft

**Comment by GentlemanII** [comment]
感谢大佬！！！&nbsp; 问题解决



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lightbrother"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月25日(星期二) 晚上7:43
收件人:&nbsp;"TISUnion/MCDaemon-go"<MCDaemon-go@noreply.github.com&gt;;
抄送:&nbsp;"    Gentleman"<1306760802@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TISUnion/MCDaemon-go] release-2.2闪退问题 (#5)



 
谢谢大佬的回复！ 修改了 jvm的最大内存 Xmx = 8192M和服务器启动文件名称
  
服务器启动文件名称
 server_name = server.jar
 服务器启动文件, 完整路径为 server_path + '/' + server_name
 server_path = minecraft
 确包服务端路径是minecraft/server.jar
 
例子：
 服务端路径：C:\user\mincecraft\1.12.2-server.jar
 server_name= 1.12.2-server.jar
 server_path = C:\user\mincecraft
