### ISSUE TITLE
是否支持服务端的cmd输入？

### ISSUE THREAD

**Issue by Sciroccogti** [TISUnion/MCDaemon-go#7]
我在启动 *MCDaemon-go* 后，发现似乎在服务器端不再能输入原有的命令，诸如`/list`等。

请问是目前不支持，还是另有输入格式？

谢谢！

**Comment by lightbrotherV** [comment]
输入指令只能启用gui才能输入，这个的确是一开始没想到的地方

**Comment by Sciroccogti** [comment]
是否有可能不伤筋动骨的情况下加上这个功能？😂

**Comment by lightbrotherV** [comment]
> 是否有可能不伤筋动骨的情况下加上这个功能？😂

目前这个工程基本不怎么维护了，在做另外一个新的

**Comment by Sciroccogti** [comment]
明白了，感谢
